### ISSUE TITLE
warning in c++20 due to == operator

### ISSUE THREAD

**Issue by Shachlan** [joboccara/NamedType#42]
```
using Foo = fluent::NamedType<int, struct FooTag, fluent::FunctionCallable, fluent::Arithmetic>;

int main(int argc, char *argv[]) {
  auto a = Foo(1);
  auto b = Foo(0);
  return (a == b) ? 0 : 1;
}
```

Compile using clang 10, get this warning:

```
main.cpp:9:13: warning: ISO C++20 considers use of overloaded operator '==' (with operand types 'fluent::NamedType<int, FooTag, fluent::FunctionCallable, fluent::Arithmetic>' and 'fluent::NamedType<int, FooTag, fluent::FunctionCallable, fluent::Arithmetic>') to be ambiguous despite there being a unique best viable function [-Wambiguous-reversed-operator]
  return (a == b) ? 0 : 1;
          ~ ^  ~
./underlying_functionalities.hpp:81:20: note: ambiguity is between a regular call to this operator and a call with the argument order reversed
    constexpr bool operator==(T const& other) const { return !(*this < other || *this > other); }
```

**Comment by joboccara** [comment]
Thanks for bringing it up! This should now be fixed with https://github.com/joboccara/NamedType/commit/bcc405100e185462f7221824229a0e060107da6c

Tbh I don't understand the rationale of the warning, and I see that other libraries such as Boost have had it too. In their thread they mention this could be a defect in clang. In the meantime we can work around the issue by defining the operator== as a friend rather than a member function.

**Comment by Shachlan** [comment]
@joboccara, I can't seem to be able to reopen this issue. 
This seems to be solved in MacOS, but I still get the warning in linux, using clang 10:

```
test.cpp:8:13: warning: ISO C++20 considers use of overloaded operator '==' (with operand types 'fluent::NamedType<int, FooTag, fluent::FunctionCallable, fluent::Arithmetic>' and 'fluent::NamedType<int, FooTag, fluent::FunctionCallable, fluent::Arithmetic>') to be ambiguous despite there being a unique best viable function [-Wambiguous-reversed-operator]
  return (a == b) ? 0 : 1;
          ~ ^  ~
./third_party/NamedType/include/NamedType/underlying_functionalities.hpp:286:44: note: ambiguity is between a regular call to this operator and a call with the argument order reversed
    FLUENT_NODISCARD friend constexpr bool operator==(Comparable<T> const& self, T const& other)
```
